# Winzorising all variables outside of the 1st and 99th percentile range

In [2]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv('~/desktop/FNCE2408/VERSION2ANALYTICS_FOR_FINANCE_M2_GROUP3_copy.csv')
df.head()

,Unnamed: 0,gvkey,datadate,fyear,indfmt,consol,popsrc,datafmt,tic,conm,...,CAPX_LAGAT,RD_LAGAT,Q,ROA,LOG_SALES,LOGMKTCAP,ZSCORE,PPENT_AT,CF,CASH
0,40603,7377,1/31/89,1988,INDL,C,D,STD,3MMINE,MIDNITE MINES INC,...,NaN,0.0,0.028986,-0.048309,NaN,NaN,NaN,0.719807,NaN,0.280193
1,61191,10548,1/31/89,1988,INDL,C,D,STD,9046B,THOR ENERGY RESOURCES INC,...,7.695652,0.0,0.710696,-0.030681,0.139249,0.610011,40.771237,0.587744,-2.236715,0.265952
2,22479,4552,1/31/89,1988,INDL,C,D,STD,3FLOGE,FALCON OIL & GAS INC,...,0.032100,0.0,0.931875,0.066380,0.275772,0.767629,1.532603,0.959353,0.024371,0.002311
3,42538,7678,1/31/89,1988,INDL,C,D,STD,NHWG,NAHAMA & WEAGANT ENERGY CO,...,0.134335,0.0,0.898150,-0.095695,0.097604,0.508580,1.200574,0.514170,-0.128138,0.394350
4,41129,7466,1/31/89,1988,INDL,C,D,STD,MND.2,MITCHELL ENERGY & DEV CORP,...,12.360717,0.0,1.014826,0.038788,2.761350,2.775793,54.601080,0.885928,-1.183318,0.011532

In [27]:
df.columns

Index(['Unnamed: 0', 'gvkey', 'datadate', 'fyear', 'indfmt', 'consol',
       'popsrc', 'datafmt', 'tic', 'conm', 'curcd', 'at', 'capx', 'ceq', 'che',
       'csho', 'dlc', 'dltt', 'ebit', 'ibc', 'oiadp', 'ppent', 're', 'sale',
       'txpd', 'wcap', 'xint', 'xrd', 'costat', 'sich', 'prcc_f', 'BLEV',
       'MLEV', 'DEBTISS_LAGAT', 'EQISS_LAGAT', 'CAPX_LAGAT', 'RD_LAGAT ', 'Q',
       'ROA ', 'LOG_SALES', 'LOGMKTCAP ', 'ZSCORE ', 'PPENT_AT ', 'CF',
       'CASH'],
      dtype='object')

In [29]:
data = ['at', 'capx', 'ceq', 'che',
       'csho', 'dlc', 'dltt', 'ebit', 'ibc', 'oiadp', 'ppent', 're', 'sale',
       'txpd', 'wcap', 'xint', 'xrd', 'sich', 'prcc_f', 'BLEV',
       'MLEV', 'DEBTISS_LAGAT', 'EQISS_LAGAT', 'CAPX_LAGAT', 'RD_LAGAT ', 'Q',
       'ROA ', 'LOG_SALES', 'LOGMKTCAP ', 'ZSCORE ', 'PPENT_AT ', 'CF',
       'CASH']
for i in data:
    firstpercentile = df[i].quantile(q=0.1)
    ninetyninthpercentile= df[i].quantile(q=0.99)
    for value in df[i]:
        if value < firstpercentile:
            dic3 = {value:firstpercentile}
            df[i].replace(dic3)
        elif value > ninetyninthpercentile:
            dic4 = {value:ninetyninthpercentile}
            df[i].replace(dic4)

In [34]:
df.to_csv('~/desktop/FNCE2408_Group3_M3Assignment.csv', index = False, header=True)